### ISSUE TITLE
Twitter OAuth Failure Leads to Broken State

### ISSUE THREAD

**Issue by weswalla** [Common-SenseMakers/sensemakers#15]
When attempting to connect my account to Twitter via the OAuth flow, the twitter endpoint failed with a 503.
![image](https://github.com/Common-SenseMakers/sensemakers/assets/39413655/430528e6-9e15-4b7a-9616-83f77afb9272)

Though it incorrectly shows me that my twitter account has been connected:
![image](https://github.com/Common-SenseMakers/sensemakers/assets/39413655/52ddaf31-2b6c-434d-ab31-27e07fba6ae0)

and in the "Editor" view it shows "not connected":
![image](https://github.com/Common-SenseMakers/sensemakers/assets/39413655/f38647fa-fb69-45c7-98d4-fccf19ed90cb)

and a continuous loading indicator in the account info modal:
![image](https://github.com/Common-SenseMakers/sensemakers/assets/39413655/62ba2f1f-d8df-479b-96a0-6cc3b730f083)

**Comment by pepoospina** [comment]
This is not applicable to the new version of the authentication flow. I will close it, thanks for highlighting it @weswalla
