### ISSUE TITLE
[NLP] moving process_kewords from st_demo

### ISSUE THREAD

**Issue by ShaRefOh** [Common-SenseMakers/sensemakers#33]
@ronentk could you move the function to a separate module like runners or something? Each time I call the function it prompts st stuff on the terminal.

**Comment by ronentk** [comment]
You can use https://github.com/Common-SenseMakers/sensemakers/blob/367d66dfc3431b64bd048bf8c2f28b9177692b48/nlp/desci_sense/shared_functions/parsers/firebase_api_parser.py#L543

directly from the parser model. This is what the st demo calls as well - 
https://github.com/Common-SenseMakers/sensemakers/blob/367d66dfc3431b64bd048bf8c2f28b9177692b48/nlp/desci_sense/demos/st_demo.py#L249

**Comment by ShaRefOh** [comment]
Ok thanks
