### ISSUE TITLE
[APP] determine how to handle `note_tweet`s (tweets longer than 280 characters)

### ISSUE THREAD

**Issue by weswalla** [Common-SenseMakers/sensemakers#49]
the docs outline a `note_tweet` field for tweets longer than 280 characters:
![image](https://github.com/Common-SenseMakers/sensemakers/assets/39413655/cb762a6c-cc63-4d6b-9d89-bb3e8a20b689)
https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/api-reference/get-users-id-tweets#tab2

the api client we are using currently doesn't support that input field as a type:
![image](https://github.com/Common-SenseMakers/sensemakers/assets/39413655/7265f956-070e-4074-9560-ecc33e61b905)

**Comment by ronentk** [comment]
Hmm do you think it is an issue with our api plan? The call we are using?
I saw this on the developer forum:
https://devcommunity.x.com/t/how-do-i-get-extra-long-tweet-text-via-v2-api/209531
Maybe it can help?

Seems they are pretty responsive on the forum if we need to ask anything.

**Comment by weswalla** [comment]
yeah that looks good. The api client we use currently doesn't support that in the types but we should be able to use `@ts-ignore` to work around that.

**Comment by weswalla** [comment]
I made a PR to update the types and support the `note_tweet` field: https://github.com/PLhery/node-twitter-api-v2/pull/526

Regardless, we will need to make sure to handle these cases wherever the full text and other entities (urls, for example) are required. Like in the UI and the NLP service. @pepoospina

**Comment by pepoospina** [comment]
This is already implemented
