### ISSUE TITLE
[APP] determine how to handle quote tweets, retweets, and replies

### ISSUE THREAD

**Issue by weswalla** [Common-SenseMakers/sensemakers#50]
from the twitter api docs (https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/api-reference/get-users-id-tweets#tab0) we can exclude `retweets` and `replies`. It seems like quote tweets are handles as normal tweets and wouldn't be excluded if `retweets` are excluded from the results.

**Comment by ronentk** [comment]
That sounds good, in line with what we defined here https://www.notion.so/m4co/Create-Twitter-science-filter-dataset-de2450d2e856421695287e6e780780e7?pvs=4

**Comment by weswalla** [comment]
@ronentk should we also exclude replies in the app as well? or are we just excluding them for the test data?

**Comment by pepoospina** [comment]
Outdated issue. Will add new one focused on threads
