### ISSUE TITLE
Keywords appearance is off

### ISSUE THREAD

**Issue by ShaRefOh** [Common-SenseMakers/sensemakers#9]
Keywords appearance looks off, it has "," at the end of each keyword
See https://nanodash.knowledgepixels.com/explore?id=RAaj4KtUSWS_qQZatPcsuH1pvEVIFbbCTRigmP0NuSv8o

@ronentk

**Comment by ronentk** [comment]
Fixed in #2 , on dev branch so will go live when @pepoospina  redeploys
